
name: http-typedi-docs
 
on: 
  # pull_request: 
  #   branches: 
  #   - main 
  #   paths: 'docs/**'
  push: 
    branches: 
    - main 
    paths: 'docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3 
      - name: Setup Node.js
        uses: actions/setup-node@v3 
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm run setup:docs

      - name: Build Package
        run: npm run docs:build
      - name: upload production artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/docs/.vitepress/dist

      # deploy
      - name: Deploy Page To Release
        id: deployment
        uses: actions/deploy-pages@v1
  docsearch:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Get the content of docsearch.json as config
        id: algolia_config
        run: echo "CONFIG=$(cat docs/docsearch.json | jq -r tostring)" >> "$GITHUB_ENV"
        shell: bash
      - name: Run algolia/docsearch-scraper image
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          docker pull algolia/docsearch-scraper:latest
          docker run --env APPLICATION_ID=${ALGOLIA_APP_ID} --env API_KEY=${ALGOLIA_API_KEY} --env "CONFIG=${CONFIG}" algolia/docsearch-scraper

