name: docsearch
on:
  schedule:
  # 约每天早上8点触发（UTC时间0点）
    - cron: '0 0 * * *'
jobs:
  algolia-schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Get the content of docsearch.json as config
        id: algolia_config
        run: echo "CONFIG=$(cat docs/docsearch.json | jq -r tostring)" >> "$GITHUB_ENV"
        shell: bash
      - name: Run algolia/docsearch-scraper image
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
        run: |
          docker pull algolia/docsearch-scraper:latest
          docker run --env APPLICATION_ID=${ALGOLIA_APP_ID} --env API_KEY=${ALGOLIA_API_KEY} --env "CONFIG=${CONFIG}" algolia/docsearch-scraper

