name: docsearch

on:
  push:
    branches:
      - main
  schedule:
  # 约每天早上8点触发（UTC时间0点）
    - cron: '0 0 * * *'
jobs:
  algolia:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: crawling
        # the `uses' attribute must be a path, a Docker image, or owner/repo@ref
        uses: darrenjennings/algolia-docsearch-action@master
        with:
          algolia_api_key: ${{ secrets.ALGOLIA_API_KEY }}
          algolia_application_id: ${{ secrets.ALGOLIA_APP_ID }}
          # needs to be inside $GITHUB_WORKSPACE from actions/checkout step
          file: docs/docsearch.json
