# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# npm ci === npm install

name: http-typedi

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - name: Get Package Version
        run: echo "::set-env name=PACKAGE_VERSION::$(node -p "require('./package.json').version")"
      - run: npm run build
      - name: Check version and publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          PREVIOUS_VERSION: ${{ env.PACKAGE_VERSION }}
        run: |
          if [ "$PACKAGE_VERSION" != "$PREVIOUS_VERSION" ]; then
            npm publish
          fi
