# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
# npm ci === npm install

name: http-typedi

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    env:
      PACKAGE_VERSION: ${{ get_package_version.outputs.version }}
      NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Get Package Version
        id: get_package_version
        run: echo "::set-output name=version::$(node -p "require('../../package.json').version")"
      - name: Publish
        run: |
          if [ "$PACKAGE_VERSION" != "${{ get_package_version.outputs.version }}" ]; then
            echo "Package version has changed. Publishing new version to NPM..."
            npm publish
          else
            echo "Package version has not changed. Skipping NPM publish."
          fi
